// // src/mail/mail.service.ts
// import { Injectable, Logger, InternalServerErrorException } from '@nestjs/common';
// import { ConfigService } from '@nestjs/config';
// import * as nodemailer from 'nodemailer';
// import { getVerificationEmailTemplate } from './templates/verification.template.js';
// import { getPasswordResetEmailTemplate } from './templates/reset-password.template.js';
// import { getLoginWelcomeEmailTemplate } from './templates/login-welcome.template.js';

// @Injectable()
// export class MailService {
//   private transporter: nodemailer.Transporter;
//   private readonly logger = new Logger(MailService.name);

//   constructor(private configService: ConfigService) {
//     this.transporter = nodemailer.createTransport({
//       host: this.configService.get<string>('SMTP_HOST'),
//       port: this.configService.get<number>('SMTP_PORT'),
//       secure: this.configService.get<number>('SMTP_PORT') === 465, // true for 465, false for other ports (like 587)
//       auth: {
//         user: this.configService.get<string>('SMTP_USER'),
//         pass: this.configService.get<string>('SMTP_PASS'),
//       },
//     });
//   }

//   /**
//    * Sends an account verification email to newly registered users with a 6-digit OTP.
//    * @param email - Recipient email address
//    * @param fullName - Recipient full name for personalization
//    * @param token - Secure 6-digit OTP token generated by AuthService
//    */
//   async sendVerificationEmail(email: string, fullName: string, token: string): Promise<void> {
//     const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://gleamlearn.vercel.app';
//     const verificationUrl = `${frontendUrl}/verify-email?token=${token}`;
//     const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';

//     // Use the passed token directly as the OTP code so it matches the database!
//     const otpCode = token;

//     const mailOptions = {
//       from: sender,
//       to: email,
//       subject: 'Verify Your Email Address - GleamLearn',
//       html: getVerificationEmailTemplate(fullName, verificationUrl, otpCode),
//     };

//     try {
//       await this.transporter.sendMail(mailOptions);
//       this.logger.log(`Verification email with OTP successfully sent to ${email}`);
//     } catch (err) {
//       const errorMessage = err instanceof Error ? err.message : String(err);
//       this.logger.error(`Failed to send verification email via Nodemailer: ${errorMessage}`);
      
//       // Fallback printout for development convenience if SMTP fails
//       console.log('----------------------------------------------------');
//       console.log('🔗 MANUAL VERIFICATION LINK FOR TESTING:');
//       console.log(verificationUrl);
//       console.log('🔑 GENERATED OTP CODE:', otpCode);
//       console.log('----------------------------------------------------');
      
//       throw new InternalServerErrorException('Could not send verification email');
//     }
//   }

//   /**
//    * Sends a password reset email when requested by a user with a 6-digit OTP.
//    * @param email - Recipient email address
//    * @param fullName - Recipient full name for personalization
//    * @param token - Secure password reset OTP token generated by AuthService
//    */
//   async sendPasswordResetEmail(email: string, fullName: string, token: string): Promise<void> {
//     const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://gleamlearn.vercel.app';
//     const resetUrl = `${frontendUrl}/reset-password?token=${token}`;
//     const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';

//     // Use the passed token directly as the OTP code so it matches the database!
//     const otpCode = token;

//     const mailOptions = {
//       from: sender,
//       to: email,
//       subject: 'Password Reset Request - GleamLearn',
//       html: getPasswordResetEmailTemplate(fullName, resetUrl, otpCode),
//     };

//     try {
//       await this.transporter.sendMail(mailOptions);
//       this.logger.log(`Password reset email with OTP successfully sent to ${email}`);
//     } catch (err) {
//       const errorMessage = err instanceof Error ? err.message : String(err);
//       this.logger.error(`Failed to send password reset email via Nodemailer: ${errorMessage}`);
      
//       // Fallback printout for development convenience if SMTP fails
//       console.log('----------------------------------------------------');
//       console.log('🔗 MANUAL PASSWORD RESET LINK FOR TESTING:');
//       console.log(resetUrl);
//       console.log('🔑 GENERATED OTP CODE:', otpCode);
//       console.log('----------------------------------------------------');
      
//       throw new InternalServerErrorException('Could not send password reset email');
//     }
//   }

//   /**
//    * Sends a welcome/login alert email upon a user successfully logging in.
//    * @param email - Recipient email address
//    * @param fullName - Recipient full name for personalization
//    */
//   async sendLoginWelcomeEmail(email: string, fullName: string): Promise<void> {
//     const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://gleamlearn.vercel.app';
//     const dashboardUrl = `${frontendUrl}/dashboard`;
//     const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';

//     const mailOptions = {
//       from: sender,
//       to: email,
//       subject: 'New Login Alert - GleamLearn',
//       html: getLoginWelcomeEmailTemplate(fullName, dashboardUrl),
//     };

//     try {
//       await this.transporter.sendMail(mailOptions);
//       this.logger.log(`Login welcome email successfully sent to ${email}`);
//     } catch (err) {
//       const errorMessage = err instanceof Error ? err.message : String(err);
//       this.logger.error(`Failed to send login welcome email via Nodemailer: ${errorMessage}`);
      
//       // Fallback printout for development convenience if SMTP fails
//       console.log('----------------------------------------------------');
//       console.log('🔗 DASHBOARD LINK:', dashboardUrl);
//       console.log('----------------------------------------------------');
//     }
//   }
// }



// src/mail/mail.service.ts
import { Injectable, Logger, InternalServerErrorException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as nodemailer from 'nodemailer';
import { getVerificationEmailTemplate } from './templates/verification.template.js';
import { getPasswordResetEmailTemplate } from './templates/reset-password.template.js';
import { getLoginWelcomeEmailTemplate } from './templates/login-welcome.template.js';
import { getPasswordResetSuccessEmailTemplate } from './templates/password-reset-success.template.js';
import { getPasswordChangedEmailTemplate } from './templates/password-changed.template.js';
import { getTwoFactorAuthEmailTemplate } from './templates/two-factor-auth.template.js';
import { getEmailChangeRequestEmailTemplate } from './templates/email-change-request.template.js';

@Injectable()
export class MailService {
  private transporter: nodemailer.Transporter;
  private readonly logger = new Logger(MailService.name);

  constructor(private configService: ConfigService) {
    this.transporter = nodemailer.createTransport({
      host: this.configService.get<string>('SMTP_HOST'),
      port: this.configService.get<number>('SMTP_PORT'),
      secure: this.configService.get<number>('SMTP_PORT') === 465, // true for 465, false for other ports (like 587)
      auth: {
        user: this.configService.get<string>('SMTP_USER'),
        pass: this.configService.get<string>('SMTP_PASS'),
      },
    });
  }

  /**
   * Sends an account verification email to newly registered users with a 6-digit OTP.
   */
  async sendVerificationEmail(email: string, fullName: string, token: string): Promise<void> {
    const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://gleamlearn.vercel.app';
    const verificationUrl = `${frontendUrl}/verify-email?token=${token}`;
    const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';
    const otpCode = token;

    const mailOptions = {
      from: sender,
      to: email,
      subject: 'Verify Your Email Address - GleamLearn',
      html: getVerificationEmailTemplate(fullName, verificationUrl, otpCode),
    };

    try {
      await this.transporter.sendMail(mailOptions);
      this.logger.log(`Verification email successfully sent to ${email}`);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to send verification email: ${errorMessage}`);
      console.log('🔗 MANUAL VERIFICATION LINK:', verificationUrl);
      console.log('🔑 OTP CODE:', otpCode);
      throw new InternalServerErrorException('Could not send verification email');
    }
  }

  /**
   * Sends a password reset email with an OTP.
   */
  async sendPasswordResetEmail(email: string, fullName: string, token: string): Promise<void> {
    const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://gleamlearn.vercel.app';
    const resetUrl = `${frontendUrl}/reset-password?token=${token}`;
    const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';
    const otpCode = token;

    const mailOptions = {
      from: sender,
      to: email,
      subject: 'Password Reset Request - GleamLearn',
      html: getPasswordResetEmailTemplate(fullName, resetUrl, otpCode),
    };

    try {
      await this.transporter.sendMail(mailOptions);
      this.logger.log(`Password reset email successfully sent to ${email}`);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to send password reset email: ${errorMessage}`);
      console.log('🔗 MANUAL PASSWORD RESET LINK:', resetUrl);
      console.log('🔑 OTP CODE:', otpCode);
      throw new InternalServerErrorException('Could not send password reset email');
    }
  }

  /**
   * Sends a new login alert email.
   */
  async sendLoginWelcomeEmail(email: string, fullName: string): Promise<void> {
    const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://gleamlearn.vercel.app';
    const resetUrl = `${frontendUrl}/settings/security`;
    const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';

    const mailOptions = {
      from: sender,
      to: email,
      subject: 'New Login Alert - GleamLearn',
      html: getLoginWelcomeEmailTemplate(
        fullName, 
        'Standard Web Browser', 
        'Chrome / Modern Browser', 
        'Unknown Location', 
        new Date().toLocaleString(), 
        resetUrl
      ),
    };

    try {
      await this.transporter.sendMail(mailOptions);
      this.logger.log(`Login welcome email successfully sent to ${email}`);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to send login welcome email: ${errorMessage}`);
    }
  }

  /**
   * Sends a confirmation email when a password has been successfully reset.
   */
  async sendPasswordResetSuccessEmail(email: string, fullName: string): Promise<void> {
    const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://gleamlearn.vercel.app';
    const signInUrl = `${frontendUrl}/login`;
    const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';

    const mailOptions = {
      from: sender,
      to: email,
      subject: 'Password Successfully Reset - GleamLearn',
      html: getPasswordResetSuccessEmailTemplate(fullName, signInUrl),
    };

    try {
      await this.transporter.sendMail(mailOptions);
      this.logger.log(`Password reset success email sent to ${email}`);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to send password reset success email: ${errorMessage}`);
    }
  }

  /**
   * Sends a notification when a user changes their password from settings.
   */
  async sendPasswordChangedEmail(email: string, fullName: string): Promise<void> {
    const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';

    const mailOptions = {
      from: sender,
      to: email,
      subject: 'Security Alert: Password Changed - GleamLearn',
      html: getPasswordChangedEmailTemplate(fullName),
    };

    try {
      await this.transporter.sendMail(mailOptions);
      this.logger.log(`Password changed notification email sent to ${email}`);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to send password changed notification: ${errorMessage}`);
    }
  }

  /**
   * Sends a Two-Factor Authentication (2FA) verification code.
   */
  async sendTwoFactorAuthEmail(email: string, fullName: string, token: string): Promise<void> {
    const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';
    const otpCode = token;

    const mailOptions = {
      from: sender,
      to: email,
      subject: 'Your Two-Factor Authentication Code - GleamLearn',
      html: getTwoFactorAuthEmailTemplate(fullName, otpCode),
    };

    try {
      await this.transporter.sendMail(mailOptions);
      this.logger.log(`2FA authentication code email sent to ${email}`);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to send 2FA email: ${errorMessage}`);
      console.log('🔑 2FA OTP CODE:', otpCode);
      throw new InternalServerErrorException('Could not send 2FA email');
    }
  }

  /**
   * Sends an OTP confirmation code when a user requests to change their email address.
   */
  async sendEmailChangeRequestEmail(email: string, fullName: string, newEmail: string, token: string): Promise<void> {
    const sender = this.configService.get<string>('MAIL_FROM') || '"GleamLearn Support" <no-reply@gleamlearn.com>';
    const otpCode = token;

    const mailOptions = {
      from: sender,
      to: email,
      subject: 'Confirm Email Address Change - GleamLearn',
      html: getEmailChangeRequestEmailTemplate(fullName, newEmail, otpCode),
    };

    try {
      await this.transporter.sendMail(mailOptions);
      this.logger.log(`Email change verification code sent to ${email}`);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to send email change request email: ${errorMessage}`);
      console.log('🔑 EMAIL CHANGE OTP CODE:', otpCode);
      throw new InternalServerErrorException('Could not send email change request email');
    }
  }
}