// src/admin/ai-moderation/entities/ai-generated-content.entity.ts
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';

@Entity('admin_ai_generated_content')
export class AiGeneratedContent {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'varchar', length: 100 })
  contentType: string; // e.g., 'QUIZ', 'LESSON_SUMMARY', 'EXPLANATION'

  @Column({ type: 'text' })
  contentPayload: string; // The text or JSON output generated by the AI

  @Column({ type: 'uuid', nullable: true })
  generatedByUserId?: string;

  @Column({ type: 'varchar', length: 30, default: 'PENDING' })
  status: string; // PENDING, APPROVED, REJECTED

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}